# Generated by Django 4.1.7 on 2023-05-15 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_image_delete_uploadimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
